<a href="https://colab.research.google.com/github/praneeth-rao/NumPy-Code-Snippets/blob/main/usefulFunctions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [18]:
import pandas as pd
import numpy as np
from scipy import stats

In [7]:
 np.array([1, 2, 3])

array([1, 2, 3])

In [8]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [9]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [10]:
np.arange(5, 11, 1)

array([ 5,  6,  7,  8,  9, 10])

In [12]:
np.linspace(1, 10, 10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [13]:
np.sum([2, 4, 4])

np.int64(10)

In [14]:
np.min([2, 4, 4]) #same way np.max

np.int64(2)

In [15]:
np.mean([2, 4, 4])

np.float64(3.3333333333333335)

In [16]:
np.median([2, 4, 4])

np.float64(4.0)

In [20]:
stats.mode([2, 4, 4])[0] # no mode function in NumPy

np.int64(4)

In [28]:
arr = np.array([-2, 4, 16])
positive_arr = np.abs(arr)
np.where(arr > 0, np.sqrt(positive_arr), np.abs(arr))

array([2., 2., 4.])

In [38]:
new_arr = np.arange(10).reshape(2, 5)
print(new_arr)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [37]:
new_arr.reshape(-1)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])